version: "3.7"
services:
  raspi-finance-endpoint:
    build:
      context: ./
      args:
       - APP=raspi-finance-endpoint
       - TIMEZONE=America/Chicago
       - USERNAME=henninb
      dockerfile: Dockerfile
    container_name: raspi-finance-endpoint
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/raspi-finance-endpoint/logs
      - ./ssl:/opt/raspi-finance-endpoint/ssl
    extra_hosts:
      - "hornsup:192.168.100.97"
    env_file:
      - env.secrets
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    expose:
      - "8086"
    env_file:
      - env.influx
      - env.secrets
networks:
  default:
    name: endpoint-net
