version: "3.7"
services:
  raspi-finance-endpoint:
    build:
      context: ./
      args:
       - APP=raspi-finance-endpoint
       - TIMEZONE=America/Chicago
       - USERNAME=henninb
      dockerfile: Dockerfile
    container_name: raspi-finance-endpoint
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    mem_limit: 1024m
    volumes:
      - ./logs:/opt/raspi-finance-endpoint/logs
      - ./ssl:/opt/raspi-finance-endpoint/ssl
      - ./excel_in:/opt/raspi-finance-endpoint/excel_in
    extra_hosts:
      - "hornsup:${HOST_IP}"
    env_file:
      - env.secrets
    depends_on:
      - influxdb-server
      - postgresql-server
  influxdb-server:
    image: influxdb:latest
    container_name: influxdb-server
    ports:
      - "8086:8086"
    expose:
      - "8086"
    env_file:
      - env.influx
      - env.secrets
  postgresql-server:
    image: postgres:12.3
    # build:
    #   context: ./
    #   dockerfile: Dockerfile-postgresql
    container_name: postgresql-server
    ports:
      - "5433:5432"
    expose:
      - "5433"
    env_file:
      - env.postgresql
    volumes:
      # - ./database-data:/var/lib/postgresql/data:z
      - ./database-data:/var/lib/postgresql/data
networks:
  default:
    name: endpoint-net
