version: "3.7"
services:
  raspi-finance-endpoint:
    image: raspi-finance-endpoint
    build:
      context: ./
      args:
       - APP=raspi-finance-endpoint
       - TIMEZONE=America/Chicago
       - USERNAME=${USER}
       - CURRENT_UID=${CURRENT_UID}
       - CURRENT_GID=${CURRENT_GID}
      dockerfile: Dockerfile
    container_name: raspi-finance-endpoint
    ports:
      - "8080:8080"
    expose:
      - "8080"
    hostname: hornsup-endpoint
    volumes:
      - ./logs:/opt/raspi-finance-endpoint/logs
      - ./excel_in:/opt/raspi-finance-endpoint/excel_in
      - ./json_in:/opt/raspi-finance-endpoint/json_in
    extra_hosts:
      - "hornsup:${HOST_IP}"
    env_file:
      - env.secrets
    depends_on:
      - grafana-server
      # - influxdb-server
  # influxdb-server:
  #   image: influxdb:1.8.3
  #   user: "${CURRENT_UID}:${CURRENT_GID}"
  #   container_name: influxdb-server
  #   volumes:
  #     - ./influxdb-data:/var/lib/influxdb
  #   ports:
  #     - "8086:8086"
  #   expose:
  #     - "8086"
  #   env_file:
  #     - env.influx
  #     - env.secrets
  grafana-server:
    image: grafana/grafana:7.3.4
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: grafana-server
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
networks:
  default:
    name: finance-net
