version: "3.7"
services:
  raspi-finance-endpoint:
    image: raspi-finance-endpoint
    build:
      context: ./
      args:
       - APP=raspi-finance-endpoint
       - TIMEZONE=America/Chicago
       - USERNAME=${USER}
      dockerfile: Dockerfile
    container_name: raspi-finance-endpoint
    ports:
      - "8080:8080"
    expose:
      - "8080"
#    mem_limit: 1024m
    hostname: hornsup-endpoint
    volumes:
      - ./logs:/opt/raspi-finance-endpoint/logs
      # - ./ssl:/opt/raspi-finance-endpoint/ssl
      - ./excel_in:/opt/raspi-finance-endpoint/excel_in
      - ./json_in:/opt/raspi-finance-endpoint/json_in
    extra_hosts:
      - "hornsup:${HOST_IP}"
    env_file:
      - env.secrets
    depends_on:
      - influxdb-server
      - postgresql-server
      - grafana-server
  influxdb-server:
    image: influxdb:1.8.3
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: influxdb-server
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    expose:
      - "8086"
    env_file:
      - env.influx
      - env.secrets
  grafana-server:
    image: grafana/grafana:7.3.4
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: grafana-server
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
  postgresql-server:
    image: postgres:13.1
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: postgresql-server
    ports:
      - "5433:5432"
    expose:
      - "5433"
    env_file:
      - env.postgresql
    hostname: postgresql-server
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
networks:
  default:
    name: finance-net
