version: "3.7"
services:
  raspi-finance-endpoint:
    image: raspi-finance-endpoint
    build:
      context: ./
      args:
       - APP=raspi-finance-endpoint
       - TIMEZONE=America/Chicago
       - USERNAME=${USER}
       - CURRENT_UID=${CURRENT_UID}
       - CURRENT_GID=${CURRENT_GID}
      dockerfile: Dockerfile
    container_name: raspi-finance-endpoint
    ports:
      - "8080:8080"
    expose:
      - "8080"
    hostname: hornsup-endpoint
    volumes:
      - ./logs:/opt/raspi-finance-endpoint/logs
      - ./excel_in:/opt/raspi-finance-endpoint/excel_in
      - ./json_in:/opt/raspi-finance-endpoint/json_in
    extra_hosts:
      - "hornsup:${HOST_IP}"
    env_file:
      - env.secrets
    depends_on:
      logstash-server:
         condition: service_healthy
    #command: ["curl", "192.168.100.97:9600"]
      # - influxdb-server
  # influxdb-server:
  #   image: influxdb:1.8.3
  #   user: "${CURRENT_UID}:${CURRENT_GID}"
  #   container_name: influxdb-server
  #   volumes:
  #     - ./influxdb-data:/var/lib/influxdb
  #   ports:
  #     - "8086:8086"
  #   expose:
  #     - "8086"
  #   env_file:
  #     - env.influx
  #     - env.secrets
  elasticsearch-server:
    image: elasticsearch:7.10.1
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: elasticsearch-server
    environment:
    #  - cluster.name=docker-cluster
    #  - bootstrap.memory_lock=true
      - discovery.type=single-node
    #  - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"
  logstash-server:
    image: logstash:7.10.1
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: logstash-server
    ports:
      - "9600:9600"
      - "4560:4560"
    expose:
      - "9600"
      - "4560"
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    healthcheck:
      test: ["CMD-SHELL", "/bin/true"]
#      test: ["CMD-SHELL", "curl", "-f", "192.168.100.97:9600"]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana-server:
    image: grafana/grafana:7.3.4
    user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: grafana-server
    ports:
      - "3001:3000"
    expose:
      - "3001"
    volumes:
      - ./grafana-data:/var/lib/grafana
      # - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    env_file:
      - env.grafana
networks:
  default:
    name: finance-net
