version: "3.7"
services:
  oracle-database-server:
    image: store/oracle/database-enterprise:12.2.0.1
    # user: "${CURRENT_UID}:${CURRENT_GID}"
    container_name: oracle-database-server
    # volumes:
    #   - /opt/oracle-data:/ORCL
    ports:
      - "1521:1521"
    expose:
      - "1521"
    environment:
      # - DB_SID=financedb
      - DUMMY=true
    # healthcheck:
    #    test: [ "CMD", "bash -c 'ps -ef| grep -v grep | grep pmon'" ]
    #    interval: 20s
    #    timeout: 5s
    #    retries: 100
  raspi-finance-endpoint:
    env_file:
      - env.prodora
    depends_on:
      oracle-database-server:
        condition: service_healthy
    restart: on-failure:10
    # command: [ "/bin/bash", "-c", "--" ]
    # args: [ "while true; do sleep 5; done;" ]
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 45s
#        max_attempts: 5
#        window: 500s

    # depends_on:
  # postgres-database:
    # condition: service_healthy

  # makes the `db` service available as the hostname `database`
  # (implies depends_on)
  # links:
  #   - oracle-database-server:database
    # environment:
    #   WAIT_HOSTS: oracle:1521
    # command:
    #   /bin/sh -c "ping 127.0.0.1 -c 10"
      # /bin/sh -c "
      #   echo Waiting for oracle service start...;
      #   while ! nc -z rabbitmq 1521;
      #   do
      #     sleep 1;
      #   done;
      #   echo Connected!;
     # "
