server:
  port: ${SERVER_PORT}
  ssl:
    key-store: classpath:hornsup-raspi-finance-keystore.p12
    key-store-password: none
    key-store-type: pkcs12
    key-alias: hornsup-raspi-finance
    key-password: none
    enabled: false
    enabled-protocols: TLSv1.2
spring:
  application:
    name: raspi-finance-endpoint
  profiles:
    active: perf

  # ===============================
  # = Jackson Settings
  # ===============================
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    mapper.accept-case-insensitive-enums: true
  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:postgresql://hornsup:5432/finance_test_db
    username: henninb
    password: monday1
    driver-class-name: org.postgresql.Driver
    # testWhileIdle to persist the connection when idle for a long period of time
    tomcat:
      test-While-Idle: true
      validation-Query: SELECT 1
    platform: postgresql
    continue-On-Error: false
    # enable initialization-mode flag to always if you want to utilize data.sql and schema.sql
    #initialization-mode: always
    initialization-mode: never

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Show or not log for each sql query
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  #    properties:
  #      hibernate:
  #        jdbc:
  #          time_zone: UTC

  # ===============================
  # = Flyway
  # ===============================
  flyway:
    enabled: true
    user: henninb
    password: monday1
    url: jdbc:postgresql://hornsup:5432/finance_test_db
    baseline-on-migrate: true
    locations: classpath:db/migration

# ===============================
# = Custom
# ===============================
custom:
  project:
    excel-password: n/a
    excel-input-file-path: excel_in
    excluded-accounts:
      - test_brian

# ===============================
# = Logging
# ===============================
#logging:
#  level:
#    org:
#      flywaydb: DEBUG
#      hibernate.SQL: WARN

#spring.jpa.hibernate.ddl-auto: none
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#none is build from schema.sql (no Java classes)
#update only add new tables in the schema.sql (starting from Java classes)

#kebab-case '-' separated

# ===============================
# = Health and Metrics
# ===============================
management:
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: true
        auto-create-db: true
        db: metrics-test
        compressed: false
        uri: http://hornsup:8086
        user-name: admin
        password:
  endpoints:
    web:
      exposure:
        include: "*"
debug: false
