server:
  port: ${SERVER_PORT}
  ssl:
    key-store: classpath:hornsup-raspi-finance-keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: pkcs12
    key-alias: hornsup-raspi-finance
    key-password: ${SSL_KEY_PASSWORD}
    enabled: ${SSL_ENABLED}
    enabled-protocols: TLSv1.2
spring:
  application:
    name: raspi-finance-endpoint
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE}

  # ===============================
  # = Jackson Settings
  # ===============================
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    mapper.accept-case-insensitive-enums: true
    time-zone: America/Chicago

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:oracle:thin:@hornsup:1521/ORCLCDB.localdomain
    #username: henninb
    username: system
    password: Oradoc_db1
    #password: monday1
    driver-class-name: oracle.jdbc.OracleDriver
    # testWhileIdle to persist the connection when idle for a long period of time
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
    continue-on-error: false
    initialization-mode: never
  thymeleaf:
    cache: false

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    #database-platform: org.hibernate.dialect
    #database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.OracleDialect
  #        jdbc:
  #          time_zone: UTC

  # ===============================
  # = Flyway
  # ===============================
  flyway:
    enabled: true
    #username: henninb
    user: system
    password: Oradoc_db1
    #password: monday1
    url: jdbc:oracle:thin:@hornsup:1521/ORCLCDB.localdomain
    baseline-on-migrate: true
    locations: classpath:db/oracle
    validate-on-migrate: true

# ===============================
# = Custom
# ===============================
custom:
  project:
    excel-password: n/a
    excel-input-file-path: n/a
    excluded-accounts:
      - test_brian
    camel-route:
      auto-start-route: true
      json-file-reader-route-id: jsonFileReaderRoute
      json-file-reader-route: "file:/opt/raspi-finance-endpoint/json_in?delete=true&moveFailed=.not-processed-failed-with-errors&delay=15000"
      transaction-to-database-route-id: transactionToDatabaseRoute
      transaction-to-database-Route: direct:transactionToDatabaseRoute
      json-file-writer-route-id: jsonFileWriterRoute
      json-file-writer-route: direct:jsonFileWriterRoute
      saved-file-endpoint: "file:/opt/raspi-finance-endpoint/json_in/.processed-successfully"
      failed-Json-file-endpoint: "file:/opt/raspi-finance-endpoint/json_in/.not-processed-non-json-file"
      failed-json-parser-endpoint: "file:/opt/raspi-finance-endpoint/json_in/.not-processed-json-parsing-errors"

# ===============================
# = Logging
# ===============================
logging:
  config: classpath:logback.groovy

#spring.jpa.hibernate.ddl-auto: none
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#none is build from schema.sql (no Java classes)
#update only add new tables in the schema.sql (starting from Java classes)

#kebab-case '-' separated

# ===============================
# = Health and Metrics
# ===============================
management:
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: false
        auto-create-db: true
        db: metrics-prodora
        compressed: false
        uri: http://hornsup:8086
        user-name: admin
        password:
  endpoints:
    web:
      exposure:
        include: "*"
debug: false
