server:
  port: ${SERVER_PORT}

spring:
  application:
    name: raspi-finance-endpoint
  profiles:
    active: basic

  # ===============================
  # = JSON
  # ===============================
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    mapper.accept-case-insensitive-enums: true

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: jdbc:h2:mem:finance_db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    # testWhileIdle to persist the connection when idle for a long period of time
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
    platform: h2
    continue-on-error: false
    schema: classpath:schema-basic-h2.sql
    data: classpath:data-basic-h2.sql
    # enable flag to always if you want to utilize data.sql and schema.sql
    initialization-mode: always
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  # Show or not log for each sql query
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: false
logging:
  level.org.hibernate.SQL: WARN

#spring.jpa.hibernate.ddl-auto: none
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#none is build from schema.sql (no Java classes)
#update only add new tables in the schema.sql (starting from Java classes)

#kebab-case '-' separated

# ===============================
# = Health and Metrics
# ===============================
management:
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: false
        auto-create-db: true
        db: metrics
        compressed: false
        uri: http://hornsup:8086
        user-name: henninb
        password: monday1
debug: false
